#! /bin/sh
sxhkd & wal -R

# wal coloring

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"

# Set the padding
bspc config window_gap 10
bspc config border_width 3
bspc top_padding 0
